const cfg=window.CBCA_SUPABASE; const sb=supabase.createClient(cfg.url,cfg.publishableKey);
const authView=document.querySelector('#authView');
const appView=document.querySelector('#appView');
const content=document.querySelector('#content');
const title=document.querySelector('#pageTitle');
const loginEmail=document.querySelector('#loginEmail');
const loginPassword=document.querySelector('#loginPassword');
let profile=null,currentView='overview';
const defs={
 members:{label:'Members',cols:['member_code','name','representative','committee_role','member_status','publication_status'],fields:[['member_code','Member code'],['name','Consultancy name','required'],['member_type','Member type','select:founding,new,associate'],['representative','Representative'],['committee_role','Committee role'],['address','Address','textarea'],['phone','Phone'],['email','Email','email'],['website','Website'],['facebook','Facebook'],['logo_url','Logo URL'],['description','Description','textarea'],['member_status','Member status','select:pending,active,suspended,expired,cancelled'],['verification_date','Verification date','date'],['expiry_date','Expiry date','date'],['publication_status','Publication','select:draft,review,published,archived']]},
 events:{label:'Events',cols:['title','event_type','starts_at','venue','event_status','publication_status'],fields:[['title','Title','required'],['summary','Summary','textarea'],['description','Description','textarea'],['event_type','Event type'],['starts_at','Starts','datetime-local'],['ends_at','Ends','datetime-local'],['venue','Venue'],['registration_url','Registration URL'],['cover_url','Cover image URL'],['event_status','Event status','select:upcoming,completed,cancelled,postponed'],['publication_status','Publication','select:draft,review,published,archived']]},
 scholarships:{label:'Scholarships',cols:['university_name','scholarship_name','application_deadline','policy_rating','last_verified_at','publication_status'],fields:[['university_name','University','required'],['scholarship_name','Scholarship','required'],['degree_levels','Degree levels'],['eligible_programs','Eligible programs','textarea'],['intake','Intake'],['application_open','Opening date','date'],['application_deadline','Deadline','date'],['tuition_coverage','Tuition coverage','textarea'],['accommodation_coverage','Accommodation','textarea'],['stipend','Stipend'],['application_fee','Application fee'],['deposit','Deposit'],['insurance_and_other_costs','Insurance and other costs','textarea'],['language_requirements','Language requirements','textarea'],['renewal_conditions','Renewal conditions','textarea'],['cancellation_conditions','Cancellation conditions','textarea'],['refund_terms','Refund terms','textarea'],['hidden_costs','Hidden costs / warnings','textarea'],['cbca_assessment','CBCA assessment','textarea'],['policy_rating','Policy rating','select:unreviewed,positive,conditional,concerning,high_risk'],['official_source_url','Official source URL','required'],['last_verified_at','Last verified','date'],['publication_status','Publication','select:draft,review,published,archived']]},
 announcements:{label:'Announcements',cols:['title','category','published_at','publication_status'],fields:[['title','Title','required'],['category','Category'],['summary','Summary','textarea'],['body','Full text','textarea'],['cover_url','Cover URL'],['published_at','Publication date','datetime-local'],['publication_status','Publication','select:draft,review,published,archived']]},
 corrections:{label:'Corrections',cols:['case_reference','organization_name','platform','case_status','response_deadline','publication_status'],fields:[['case_reference','Case reference'],['organization_name','Organization','required'],['platform','Platform'],['post_url','Post URL'],['incorrect_claim','Incorrect claim','textarea|required'],['verified_information','Verified information','textarea|required'],['official_source_url','Official source URL'],['evidence_url','Evidence URL'],['notice_sent_at','Notice sent','datetime-local'],['response_deadline','Response deadline','datetime-local'],['response_text','Response','textarea'],['internal_notes','Internal notes','textarea'],['resolution','Resolution','textarea'],['case_status','Case status','select:submitted,under_review,evidence_requested,notice_sent,response_received,mediation,resolved,referred,closed,rejected'],['public_summary','Public summary','textarea'],['publication_status','Publication','select:draft,review,published,archived']]},
 applications:{label:'Membership applications',table:'membership_applications',cols:['case_reference','consultancy_name','representative','contact_email','status','created_at'],readonly:true},
 complaints:{label:'Complaints',table:'complaints',cols:['case_reference','complainant_name','accused_organization','case_status','created_at'],readonly:true},
 admins:{label:'Administrators',table:'allowed_admins',cols:['email','role','active','added_at'],fields:[['email','Email','email|required'],['role','Role','select:pending,content_editor,reviewer,complaint_officer,super_admin'],['active','Active','checkbox'],['note','Note','textarea']]}
};
function toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function esc(s=''){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v){if(v===null||v===undefined||v==='')return '—'; if(typeof v==='boolean')return v?'Yes':'No'; if(String(v).includes('T')){const d=new Date(v);if(!isNaN(d))return d.toLocaleString()} return esc(v)}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session)return showAuth();const {data,error}=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(error||!data||data.role==='pending'||!data.active){await sb.auth.signOut();showAuth();return toast('This account is not authorized yet.')}profile=data;authView.hidden=true;appView.hidden=false;document.querySelector('#userInfo').textContent=`${profile.email} · ${profile.role.replaceAll('_',' ')}`;render('overview')}
function showAuth(){authView.hidden=false;appView.hidden=true}
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=loginEmail.value.trim(),password=loginPassword.value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);boot()});
document.querySelector('#signupBtn').onclick=async()=>{const email=loginEmail.value.trim(),password=loginPassword.value;if(!email||password.length<8)return toast('Enter the approved email and a password of at least 8 characters.');const {error}=await sb.auth.signUp({email,password});toast(error?error.message:'Account created. Check the email inbox if confirmation is enabled.')};
document.querySelector('#resetBtn').onclick=async()=>{const email=loginEmail.value.trim();if(!email)return toast('Enter your email first.');const {error}=await sb.auth.resetPasswordForEmail(email);toast(error?error.message:'Password reset email sent.')};
document.querySelector('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
sb.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){const p=prompt('Enter a new password (minimum 8 characters):');if(p)sb.auth.updateUser({password:p}).then(({error})=>toast(error?error.message:'Password updated.'));}});
document.querySelectorAll('#sideNav button').forEach(b=>b.onclick=()=>render(b.dataset.view));
async function render(view){currentView=view;document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));title.textContent=view==='overview'?'Overview':defs[view].label;if(view==='overview')return overview();return list(view)}
async function overview(){const tables=['members','events','scholarships','announcements'];const counts={};for(const t of tables){const {count}=await sb.from(t).select('*',{count:'exact',head:true});counts[t]=count||0}content.innerHTML=`<div class="stats">${tables.map(t=>`<div class="stat"><span>${t}</span><strong>${counts[t]}</strong><small>database records</small></div>`).join('')}</div><div class="panel"><h2>Publishing control</h2><p>Editors prepare drafts. Only a Reviewer or Super Admin can set a record to <b>published</b>. Public pages read only published records.</p></div><div class="panel"><h2>System status</h2><p>Supabase connected. Signed in as <span class="badge">${esc(profile.role)}</span>.</p><p class="note">Do not place any service-role key, database password, or JWT secret in this website.</p></div>`}
async function list(view){const d=defs[view],table=d.table||view;content.innerHTML='<div class="panel"><div class="empty">Loading…</div></div>';const {data,error}=await sb.from(table).select('*').order('created_at',{ascending:false});if(error){content.innerHTML=`<div class="panel"><div class="empty">${esc(error.message)}</div></div>`;return}content.innerHTML=`<div class="panel"><div class="panel-head"><div><h2>${d.label}</h2><p class="note">${data.length} record(s)</p></div><div class="toolbar">${d.fields?`<button id="addBtn">+ Add record</button>`:''}<button class="secondary" id="refreshBtn">Refresh</button></div></div><div class="table-wrap"><table><thead><tr>${d.cols.map(c=>`<th>${c.replaceAll('_',' ')}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${data.length?data.map(r=>`<tr>${d.cols.map(c=>`<td>${c.includes('status')||c==='role'?`<span class="badge">${fmt(r[c])}</span>`:fmt(r[c])}</td>`).join('')}<td><div class="row-actions"><button class="secondary" data-edit="${r.id||r.email}">View/Edit</button>${!d.readonly&&profile.role==='super_admin'&&table!=='allowed_admins'?`<button class="danger" data-del="${r.id}">Delete</button>`:''}</div></td></tr>`).join(''):`<tr><td colspan="${d.cols.length+1}" class="empty">No records yet.</td></tr>`}</tbody></table></div></div>`;document.querySelector('#refreshBtn').onclick=()=>list(view);document.querySelector('#addBtn')?.addEventListener('click',()=>openForm(view,null));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(view,data.find(r=>(r.id||r.email)===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(table,b.dataset.del));}
function fieldHtml(f,r={}){let [name,label,type='text']=f;const req=type.includes('required')||f.includes('required');type=type.replace('|required','');const val=r[name]??'';if(type==='textarea')return `<label class="field span-2">${label}<textarea name="${name}" ${req?'required':''}>${esc(val)}</textarea></label>`;if(type.startsWith('select:'))return `<label class="field">${label}<select name="${name}">${type.slice(7).split(',').map(x=>`<option value="${x}" ${val===x?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}</select></label>`;if(type==='checkbox')return `<label class="field">${label}<input name="${name}" type="checkbox" ${val!==false?'checked':''}></label>`;let v=val;if(type==='datetime-local'&&v)v=String(v).slice(0,16);return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(v)}" ${req?'required':''}></label>`}
function openForm(view,r){const d=defs[view],table=d.table||view;if(d.readonly){return openCase(view,r)}const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>${r?'Edit':'Add'} ${d.label}</h2><button class="close">Close</button></div><form id="recordForm" class="form-grid grid-2">${d.fields.map(f=>fieldHtml(f,r||{})).join('')}<div class="span-2 toolbar"><button type="submit">Save</button><button class="secondary close" type="button">Cancel</button></div></form></div>`;document.body.append(m);m.querySelectorAll('.close').forEach(b=>b.onclick=()=>m.remove());m.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),obj={};for(const [k,v] of fd){const input=e.target.elements[k];obj[k]=input.type==='checkbox'?input.checked:(v===''?null:v)};let q;if(r){const key=table==='allowed_admins'?'email':'id';q=sb.from(table).update(obj).eq(key,r[key])}else q=sb.from(table).insert(obj);const {error}=await q;if(error)return toast(error.message);toast('Saved successfully.');m.remove();list(view)}}
function openCase(view,r){const d=defs[view],table=d.table||view;const m=document.createElement('div');m.className='modal';const editable=view==='complaints'?[['case_status','Case status','select:submitted,under_review,evidence_requested,notice_sent,response_received,mediation,resolved,referred,closed,rejected'],['internal_notes','Internal notes','textarea'],['resolution','Resolution','textarea']]:[['status','Application status','select:submitted,under_review,documents_requested,inspection_scheduled,approved,rejected,withdrawn'],['review_notes','Review notes','textarea']];m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>${d.label}</h2><button class="close">Close</button></div><div class="panel">${Object.entries(r).filter(([k])=>!['internal_notes','review_notes','resolution'].includes(k)).map(([k,v])=>`<p><b>${esc(k.replaceAll('_',' '))}:</b> ${fmt(v)}</p>`).join('')}</div><form class="form-grid grid-2">${editable.map(f=>fieldHtml(f,r)).join('')}<div class="span-2"><button>Update case</button></div></form></div>`;document.body.append(m);m.querySelector('.close').onclick=()=>m.remove();m.querySelector('form').onsubmit=async e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.target));const {error}=await sb.from(table).update(obj).eq('id',r.id);if(error)return toast(error.message);toast('Case updated.');m.remove();list(view)}}
async function remove(table,id){if(!confirm('Permanently delete this record?'))return;const {error}=await sb.from(table).delete().eq('id',id);toast(error?error.message:'Deleted.');if(!error)list(currentView)}
boot();